export default function Lineup() {
	return (
		<div id="lineup_container">
			<p className="lineup">
				FLUME • WEEZER THE SHINS • THIRTY SECONDS TO MARS DILLON FRANCIS • MIIKE SNOW • GLASS ANIMALS • TORY LANEZ • PHANTOGRAM AFI CAPITAL • CITIES OK GO THE NAKED AND FAMOUS KALEO • BUSTA RHYMES • BANKS 0.A.R. BLEACHERS BENNY BENASSI • LIL DICKY•MISTERWIVES T-PAIN • DJ JAZZY JEFF • WALE BOB MOSES • NAHKO AND MEDICINE FOR THE PEOPLE • DAYA MATOMA ILLENIUM KESHA FRANZ FERDINAND GALANTIS • SNAKEHIPS • CASHMERE CAT THE STRUMBELLAS • GRYFFIN FRANCIS AND THE LIGHTS STICK FIGURE • SLUSHII • NF BIG
				WILD EDEN THE WHITE PANDA BISHOP BRIGGS HAMILTON LEITHAUSER.SIR SLY • LEWIS DEL MAR JUDAH & THE LION K. FLAY MUNA SOFI TUKKER MAGIC GIANT • MEG MAC • RAINBOW KITTEN SURPRISE SUNFLOWER BEAN ARIZONA SIR THE BAPTISI • CRYWOLF ELOHIM FICKLE FRIENDS • SIEVE JAMES • DREAMERS • WIN AND W00 ALEX WILEY SECRET WEAPONS • YOUNG BOMBS ANDY FRASCO & THE U.N. AYOKAY GOODY GRACE • MONDO COZHO • NAWAS. ROZES. SAINT WKND•SAVOIR ADORE LAWRENCE SPIRITUAL REZ SALT CATHEDRAL JARED & THE MILL SUB-RADIO WARM
				BREW • ALAN WALKER • MAGGIE ROGERS JACOB BANKS SAM FELDT • BARNS COURTNEY ANNA LUNOE JONAS BLUE BLOSSOHS • QUINN XCII JAMES TW KAIYDO PARDISONFONTAINE.HANDSOME GHOST • KEVIN GARRETT • 888 SHAED TAYLOR BENNETT • FOREIGN AIR • CVBZDEAD MAN FALL.WILDERADO FLETCHER HAMISH ANDERSON NEW MADRID THE ORPHAN THE POET WALKER LUKENS ROADKILL GHOST CHOIR OWEL THE STEPPIN STONES THE SOCIAL ANIMALS • REPEAT REPEAI DEAL CASINO ANIMAL YEARS COLD ROSES CARVERTON MICHAEL BLUME HDBEENDOPE LOUIE LOUIE
				TRIO•SHIZZ LO THE LAWSUITS • FUTURE GENERATIONS • VITA AND THE WOOLF ODDKIDOUT.QUITEHYPE • SHORT SLEEVE HEART ASTRO 8000 BENCOOLEN HIR FONTANE. ARMANI LEE • DUDE RANCH & THE GIRL AT THE ROCK SHOW-CHILL MOODY. JOIE KATHOST
			</p>
			<button className="secondary" id="schedule_btn">
				Schedule
			</button>
		</div>
	);
}
